# Generated by Django 3.2.9 on 2021-12-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retroCar', '0003_auto_20211202_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='cat',
        ),
        migrations.RemoveField(
            model_name='category',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='category',
            name='time_update',
        ),
    ]
